/*=============================================================================
  Carnival Gaming HOL — Admin Setup Script
  Run as ACCOUNTADMIN on SFSENORTHAMERICA-HOL_CARNIVAL
  Creates 10 HOL users with isolated databases, warehouses, and roles.
=============================================================================*/

USE ROLE ACCOUNTADMIN;

-- Create a shared database for the gaming data stage
CREATE DATABASE IF NOT EXISTS HOL_SHARED;
CREATE SCHEMA IF NOT EXISTS HOL_SHARED.PUBLIC;

-- Create an internal stage for CSV data files
CREATE OR REPLACE STAGE HOL_SHARED.PUBLIC.GAMING_DATA
  DIRECTORY = (ENABLE = TRUE)
  COMMENT = 'Shared stage with cruise gaming CSV data for all HOL users';

-- Loop to create 10 users
-- (Snowflake doesn't support procedural loops in worksheets easily,
--  so we use explicit statements for clarity in a lab setting)

----------------------------------------------------------------------
-- USER 01
----------------------------------------------------------------------
CREATE ROLE IF NOT EXISTS HOL_USER_01_ROLE;
CREATE WAREHOUSE IF NOT EXISTS HOL_USER_01_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;
GRANT USAGE ON WAREHOUSE HOL_USER_01_WH TO ROLE HOL_USER_01_ROLE;
GRANT OPERATE ON WAREHOUSE HOL_USER_01_WH TO ROLE HOL_USER_01_ROLE;

CREATE DATABASE IF NOT EXISTS HOL_USER_01_DB;
GRANT OWNERSHIP ON DATABASE HOL_USER_01_DB TO ROLE HOL_USER_01_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL SCHEMAS IN DATABASE HOL_USER_01_DB TO ROLE HOL_USER_01_ROLE COPY CURRENT GRANTS;

CREATE USER IF NOT EXISTS HOL_USER_01
  PASSWORD = 'SnowHOL2026!'
  DEFAULT_ROLE = HOL_USER_01_ROLE
  DEFAULT_WAREHOUSE = HOL_USER_01_WH
  DEFAULT_NAMESPACE = HOL_USER_01_DB.PUBLIC
  MUST_CHANGE_PASSWORD = FALSE;
GRANT ROLE HOL_USER_01_ROLE TO USER HOL_USER_01;

----------------------------------------------------------------------
-- USER 02
----------------------------------------------------------------------
CREATE ROLE IF NOT EXISTS HOL_USER_02_ROLE;
CREATE WAREHOUSE IF NOT EXISTS HOL_USER_02_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;
GRANT USAGE ON WAREHOUSE HOL_USER_02_WH TO ROLE HOL_USER_02_ROLE;
GRANT OPERATE ON WAREHOUSE HOL_USER_02_WH TO ROLE HOL_USER_02_ROLE;

CREATE DATABASE IF NOT EXISTS HOL_USER_02_DB;
GRANT OWNERSHIP ON DATABASE HOL_USER_02_DB TO ROLE HOL_USER_02_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL SCHEMAS IN DATABASE HOL_USER_02_DB TO ROLE HOL_USER_02_ROLE COPY CURRENT GRANTS;

CREATE USER IF NOT EXISTS HOL_USER_02
  PASSWORD = 'SnowHOL2026!'
  DEFAULT_ROLE = HOL_USER_02_ROLE
  DEFAULT_WAREHOUSE = HOL_USER_02_WH
  DEFAULT_NAMESPACE = HOL_USER_02_DB.PUBLIC
  MUST_CHANGE_PASSWORD = FALSE;
GRANT ROLE HOL_USER_02_ROLE TO USER HOL_USER_02;

----------------------------------------------------------------------
-- USER 03
----------------------------------------------------------------------
CREATE ROLE IF NOT EXISTS HOL_USER_03_ROLE;
CREATE WAREHOUSE IF NOT EXISTS HOL_USER_03_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;
GRANT USAGE ON WAREHOUSE HOL_USER_03_WH TO ROLE HOL_USER_03_ROLE;
GRANT OPERATE ON WAREHOUSE HOL_USER_03_WH TO ROLE HOL_USER_03_ROLE;

CREATE DATABASE IF NOT EXISTS HOL_USER_03_DB;
GRANT OWNERSHIP ON DATABASE HOL_USER_03_DB TO ROLE HOL_USER_03_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL SCHEMAS IN DATABASE HOL_USER_03_DB TO ROLE HOL_USER_03_ROLE COPY CURRENT GRANTS;

CREATE USER IF NOT EXISTS HOL_USER_03
  PASSWORD = 'SnowHOL2026!'
  DEFAULT_ROLE = HOL_USER_03_ROLE
  DEFAULT_WAREHOUSE = HOL_USER_03_WH
  DEFAULT_NAMESPACE = HOL_USER_03_DB.PUBLIC
  MUST_CHANGE_PASSWORD = FALSE;
GRANT ROLE HOL_USER_03_ROLE TO USER HOL_USER_03;

----------------------------------------------------------------------
-- USER 04
----------------------------------------------------------------------
CREATE ROLE IF NOT EXISTS HOL_USER_04_ROLE;
CREATE WAREHOUSE IF NOT EXISTS HOL_USER_04_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;
GRANT USAGE ON WAREHOUSE HOL_USER_04_WH TO ROLE HOL_USER_04_ROLE;
GRANT OPERATE ON WAREHOUSE HOL_USER_04_WH TO ROLE HOL_USER_04_ROLE;

CREATE DATABASE IF NOT EXISTS HOL_USER_04_DB;
GRANT OWNERSHIP ON DATABASE HOL_USER_04_DB TO ROLE HOL_USER_04_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL SCHEMAS IN DATABASE HOL_USER_04_DB TO ROLE HOL_USER_04_ROLE COPY CURRENT GRANTS;

CREATE USER IF NOT EXISTS HOL_USER_04
  PASSWORD = 'SnowHOL2026!'
  DEFAULT_ROLE = HOL_USER_04_ROLE
  DEFAULT_WAREHOUSE = HOL_USER_04_WH
  DEFAULT_NAMESPACE = HOL_USER_04_DB.PUBLIC
  MUST_CHANGE_PASSWORD = FALSE;
GRANT ROLE HOL_USER_04_ROLE TO USER HOL_USER_04;

----------------------------------------------------------------------
-- USER 05
----------------------------------------------------------------------
CREATE ROLE IF NOT EXISTS HOL_USER_05_ROLE;
CREATE WAREHOUSE IF NOT EXISTS HOL_USER_05_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;
GRANT USAGE ON WAREHOUSE HOL_USER_05_WH TO ROLE HOL_USER_05_ROLE;
GRANT OPERATE ON WAREHOUSE HOL_USER_05_WH TO ROLE HOL_USER_05_ROLE;

CREATE DATABASE IF NOT EXISTS HOL_USER_05_DB;
GRANT OWNERSHIP ON DATABASE HOL_USER_05_DB TO ROLE HOL_USER_05_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL SCHEMAS IN DATABASE HOL_USER_05_DB TO ROLE HOL_USER_05_ROLE COPY CURRENT GRANTS;

CREATE USER IF NOT EXISTS HOL_USER_05
  PASSWORD = 'SnowHOL2026!'
  DEFAULT_ROLE = HOL_USER_05_ROLE
  DEFAULT_WAREHOUSE = HOL_USER_05_WH
  DEFAULT_NAMESPACE = HOL_USER_05_DB.PUBLIC
  MUST_CHANGE_PASSWORD = FALSE;
GRANT ROLE HOL_USER_05_ROLE TO USER HOL_USER_05;

----------------------------------------------------------------------
-- USER 06
----------------------------------------------------------------------
CREATE ROLE IF NOT EXISTS HOL_USER_06_ROLE;
CREATE WAREHOUSE IF NOT EXISTS HOL_USER_06_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;
GRANT USAGE ON WAREHOUSE HOL_USER_06_WH TO ROLE HOL_USER_06_ROLE;
GRANT OPERATE ON WAREHOUSE HOL_USER_06_WH TO ROLE HOL_USER_06_ROLE;

CREATE DATABASE IF NOT EXISTS HOL_USER_06_DB;
GRANT OWNERSHIP ON DATABASE HOL_USER_06_DB TO ROLE HOL_USER_06_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL SCHEMAS IN DATABASE HOL_USER_06_DB TO ROLE HOL_USER_06_ROLE COPY CURRENT GRANTS;

CREATE USER IF NOT EXISTS HOL_USER_06
  PASSWORD = 'SnowHOL2026!'
  DEFAULT_ROLE = HOL_USER_06_ROLE
  DEFAULT_WAREHOUSE = HOL_USER_06_WH
  DEFAULT_NAMESPACE = HOL_USER_06_DB.PUBLIC
  MUST_CHANGE_PASSWORD = FALSE;
GRANT ROLE HOL_USER_06_ROLE TO USER HOL_USER_06;

----------------------------------------------------------------------
-- USER 07
----------------------------------------------------------------------
CREATE ROLE IF NOT EXISTS HOL_USER_07_ROLE;
CREATE WAREHOUSE IF NOT EXISTS HOL_USER_07_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;
GRANT USAGE ON WAREHOUSE HOL_USER_07_WH TO ROLE HOL_USER_07_ROLE;
GRANT OPERATE ON WAREHOUSE HOL_USER_07_WH TO ROLE HOL_USER_07_ROLE;

CREATE DATABASE IF NOT EXISTS HOL_USER_07_DB;
GRANT OWNERSHIP ON DATABASE HOL_USER_07_DB TO ROLE HOL_USER_07_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL SCHEMAS IN DATABASE HOL_USER_07_DB TO ROLE HOL_USER_07_ROLE COPY CURRENT GRANTS;

CREATE USER IF NOT EXISTS HOL_USER_07
  PASSWORD = 'SnowHOL2026!'
  DEFAULT_ROLE = HOL_USER_07_ROLE
  DEFAULT_WAREHOUSE = HOL_USER_07_WH
  DEFAULT_NAMESPACE = HOL_USER_07_DB.PUBLIC
  MUST_CHANGE_PASSWORD = FALSE;
GRANT ROLE HOL_USER_07_ROLE TO USER HOL_USER_07;

----------------------------------------------------------------------
-- USER 08
----------------------------------------------------------------------
CREATE ROLE IF NOT EXISTS HOL_USER_08_ROLE;
CREATE WAREHOUSE IF NOT EXISTS HOL_USER_08_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;
GRANT USAGE ON WAREHOUSE HOL_USER_08_WH TO ROLE HOL_USER_08_ROLE;
GRANT OPERATE ON WAREHOUSE HOL_USER_08_WH TO ROLE HOL_USER_08_ROLE;

CREATE DATABASE IF NOT EXISTS HOL_USER_08_DB;
GRANT OWNERSHIP ON DATABASE HOL_USER_08_DB TO ROLE HOL_USER_08_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL SCHEMAS IN DATABASE HOL_USER_08_DB TO ROLE HOL_USER_08_ROLE COPY CURRENT GRANTS;

CREATE USER IF NOT EXISTS HOL_USER_08
  PASSWORD = 'SnowHOL2026!'
  DEFAULT_ROLE = HOL_USER_08_ROLE
  DEFAULT_WAREHOUSE = HOL_USER_08_WH
  DEFAULT_NAMESPACE = HOL_USER_08_DB.PUBLIC
  MUST_CHANGE_PASSWORD = FALSE;
GRANT ROLE HOL_USER_08_ROLE TO USER HOL_USER_08;

----------------------------------------------------------------------
-- USER 09
----------------------------------------------------------------------
CREATE ROLE IF NOT EXISTS HOL_USER_09_ROLE;
CREATE WAREHOUSE IF NOT EXISTS HOL_USER_09_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;
GRANT USAGE ON WAREHOUSE HOL_USER_09_WH TO ROLE HOL_USER_09_ROLE;
GRANT OPERATE ON WAREHOUSE HOL_USER_09_WH TO ROLE HOL_USER_09_ROLE;

CREATE DATABASE IF NOT EXISTS HOL_USER_09_DB;
GRANT OWNERSHIP ON DATABASE HOL_USER_09_DB TO ROLE HOL_USER_09_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL SCHEMAS IN DATABASE HOL_USER_09_DB TO ROLE HOL_USER_09_ROLE COPY CURRENT GRANTS;

CREATE USER IF NOT EXISTS HOL_USER_09
  PASSWORD = 'SnowHOL2026!'
  DEFAULT_ROLE = HOL_USER_09_ROLE
  DEFAULT_WAREHOUSE = HOL_USER_09_WH
  DEFAULT_NAMESPACE = HOL_USER_09_DB.PUBLIC
  MUST_CHANGE_PASSWORD = FALSE;
GRANT ROLE HOL_USER_09_ROLE TO USER HOL_USER_09;

----------------------------------------------------------------------
-- USER 10
----------------------------------------------------------------------
CREATE ROLE IF NOT EXISTS HOL_USER_10_ROLE;
CREATE WAREHOUSE IF NOT EXISTS HOL_USER_10_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;
GRANT USAGE ON WAREHOUSE HOL_USER_10_WH TO ROLE HOL_USER_10_ROLE;
GRANT OPERATE ON WAREHOUSE HOL_USER_10_WH TO ROLE HOL_USER_10_ROLE;

CREATE DATABASE IF NOT EXISTS HOL_USER_10_DB;
GRANT OWNERSHIP ON DATABASE HOL_USER_10_DB TO ROLE HOL_USER_10_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL SCHEMAS IN DATABASE HOL_USER_10_DB TO ROLE HOL_USER_10_ROLE COPY CURRENT GRANTS;

CREATE USER IF NOT EXISTS HOL_USER_10
  PASSWORD = 'SnowHOL2026!'
  DEFAULT_ROLE = HOL_USER_10_ROLE
  DEFAULT_WAREHOUSE = HOL_USER_10_WH
  DEFAULT_NAMESPACE = HOL_USER_10_DB.PUBLIC
  MUST_CHANGE_PASSWORD = FALSE;
GRANT ROLE HOL_USER_10_ROLE TO USER HOL_USER_10;

----------------------------------------------------------------------
-- SHARED GRANTS (all 10 users)
----------------------------------------------------------------------

-- Grant access to shared data stage
GRANT USAGE ON DATABASE HOL_SHARED TO ROLE HOL_USER_01_ROLE;
GRANT USAGE ON DATABASE HOL_SHARED TO ROLE HOL_USER_02_ROLE;
GRANT USAGE ON DATABASE HOL_SHARED TO ROLE HOL_USER_03_ROLE;
GRANT USAGE ON DATABASE HOL_SHARED TO ROLE HOL_USER_04_ROLE;
GRANT USAGE ON DATABASE HOL_SHARED TO ROLE HOL_USER_05_ROLE;
GRANT USAGE ON DATABASE HOL_SHARED TO ROLE HOL_USER_06_ROLE;
GRANT USAGE ON DATABASE HOL_SHARED TO ROLE HOL_USER_07_ROLE;
GRANT USAGE ON DATABASE HOL_SHARED TO ROLE HOL_USER_08_ROLE;
GRANT USAGE ON DATABASE HOL_SHARED TO ROLE HOL_USER_09_ROLE;
GRANT USAGE ON DATABASE HOL_SHARED TO ROLE HOL_USER_10_ROLE;

GRANT USAGE ON SCHEMA HOL_SHARED.PUBLIC TO ROLE HOL_USER_01_ROLE;
GRANT USAGE ON SCHEMA HOL_SHARED.PUBLIC TO ROLE HOL_USER_02_ROLE;
GRANT USAGE ON SCHEMA HOL_SHARED.PUBLIC TO ROLE HOL_USER_03_ROLE;
GRANT USAGE ON SCHEMA HOL_SHARED.PUBLIC TO ROLE HOL_USER_04_ROLE;
GRANT USAGE ON SCHEMA HOL_SHARED.PUBLIC TO ROLE HOL_USER_05_ROLE;
GRANT USAGE ON SCHEMA HOL_SHARED.PUBLIC TO ROLE HOL_USER_06_ROLE;
GRANT USAGE ON SCHEMA HOL_SHARED.PUBLIC TO ROLE HOL_USER_07_ROLE;
GRANT USAGE ON SCHEMA HOL_SHARED.PUBLIC TO ROLE HOL_USER_08_ROLE;
GRANT USAGE ON SCHEMA HOL_SHARED.PUBLIC TO ROLE HOL_USER_09_ROLE;
GRANT USAGE ON SCHEMA HOL_SHARED.PUBLIC TO ROLE HOL_USER_10_ROLE;

GRANT READ ON STAGE HOL_SHARED.PUBLIC.GAMING_DATA TO ROLE HOL_USER_01_ROLE;
GRANT READ ON STAGE HOL_SHARED.PUBLIC.GAMING_DATA TO ROLE HOL_USER_02_ROLE;
GRANT READ ON STAGE HOL_SHARED.PUBLIC.GAMING_DATA TO ROLE HOL_USER_03_ROLE;
GRANT READ ON STAGE HOL_SHARED.PUBLIC.GAMING_DATA TO ROLE HOL_USER_04_ROLE;
GRANT READ ON STAGE HOL_SHARED.PUBLIC.GAMING_DATA TO ROLE HOL_USER_05_ROLE;
GRANT READ ON STAGE HOL_SHARED.PUBLIC.GAMING_DATA TO ROLE HOL_USER_06_ROLE;
GRANT READ ON STAGE HOL_SHARED.PUBLIC.GAMING_DATA TO ROLE HOL_USER_07_ROLE;
GRANT READ ON STAGE HOL_SHARED.PUBLIC.GAMING_DATA TO ROLE HOL_USER_08_ROLE;
GRANT READ ON STAGE HOL_SHARED.PUBLIC.GAMING_DATA TO ROLE HOL_USER_09_ROLE;
GRANT READ ON STAGE HOL_SHARED.PUBLIC.GAMING_DATA TO ROLE HOL_USER_10_ROLE;

-- Grant Cortex AI privileges to all users
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE HOL_USER_01_ROLE;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE HOL_USER_02_ROLE;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE HOL_USER_03_ROLE;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE HOL_USER_04_ROLE;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE HOL_USER_05_ROLE;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE HOL_USER_06_ROLE;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE HOL_USER_07_ROLE;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE HOL_USER_08_ROLE;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE HOL_USER_09_ROLE;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE HOL_USER_10_ROLE;

-- Grant CREATE SNOWFLAKE.ML.ANOMALY_DETECTION, etc. if needed
-- Grant IMPORTED PRIVILEGES on SNOWFLAKE DB for AI functions
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE HOL_USER_01_ROLE;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE HOL_USER_02_ROLE;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE HOL_USER_03_ROLE;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE HOL_USER_04_ROLE;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE HOL_USER_05_ROLE;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE HOL_USER_06_ROLE;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE HOL_USER_07_ROLE;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE HOL_USER_08_ROLE;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE HOL_USER_09_ROLE;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE HOL_USER_10_ROLE;

-- ==========================================================================
-- Account-level privileges the lab needs
--
-- These were applied live during lab prep and are recorded here so the whole
-- environment can be rebuilt from this script alone.
-- ==========================================================================

EXECUTE IMMEDIATE $$
DECLARE
  i INT DEFAULT 1;
  r VARCHAR;
BEGIN
  WHILE (i <= 10) DO
    r := 'HOL_USER_' || LPAD(i::VARCHAR, 2, '0') || '_ROLE';

    -- Section 1 and the Snowpark notebook let users create their own objects.
    EXECUTE IMMEDIATE 'GRANT CREATE DATABASE ON ACCOUNT TO ROLE ' || r;

    -- So users can inspect their own warehouse activity.
    EXECUTE IMMEDIATE 'GRANT MONITOR ON WAREHOUSE HOL_USER_'
                      || LPAD(i::VARCHAR, 2, '0') || '_WH TO ROLE ' || r;
    i := i + 1;
  END WHILE;
  RETURN 'Granted account-level lab privileges to 10 roles';
END;
$$;


-- ==========================================================================
-- Snowflake CoWork object
--
-- This account HAS a CoWork object, which means CoWork shows a curated list:
-- an agent is only visible there if it has been explicitly added. Without
-- this object, CoWork would show every agent a user can access.
--
-- Section 6 has each user register their own agent, so they need MODIFY.
-- MODIFY is account-wide on this single shared object, but adding and
-- removing agents is still gated by USAGE on the agent itself -- verified:
-- a user cannot add or drop another user's agent, and SHOW AGENTS only
-- lists agents they can access.
--
-- CAVEAT: MODIFY also permits changing shared CoWork branding (display name,
-- welcome message, theme). Verified that a HOL role can do this. It affects
-- every user in the account. Acceptable for a facilitated lab; do not grant
-- MODIFY this way in a shared production account.
-- ==========================================================================

CREATE SNOWFLAKE INTELLIGENCE IF NOT EXISTS SNOWFLAKE_INTELLIGENCE_OBJECT_DEFAULT;

GRANT USAGE ON SNOWFLAKE INTELLIGENCE SNOWFLAKE_INTELLIGENCE_OBJECT_DEFAULT
  TO ROLE PUBLIC;

EXECUTE IMMEDIATE $$
DECLARE
  i INT DEFAULT 1;
  r VARCHAR;
BEGIN
  WHILE (i <= 10) DO
    r := 'HOL_USER_' || LPAD(i::VARCHAR, 2, '0') || '_ROLE';
    EXECUTE IMMEDIATE 'GRANT MODIFY ON SNOWFLAKE INTELLIGENCE '
                      || 'SNOWFLAKE_INTELLIGENCE_OBJECT_DEFAULT TO ROLE ' || r;
    EXECUTE IMMEDIATE 'GRANT USAGE ON SNOWFLAKE INTELLIGENCE '
                      || 'SNOWFLAKE_INTELLIGENCE_OBJECT_DEFAULT TO ROLE ' || r;
    i := i + 1;
  END WHILE;
  RETURN 'Granted CoWork MODIFY + USAGE to 10 roles';
END;
$$;


-- Verify setup
SELECT 'Setup complete. All 10 users provisioned.' AS status;
