/*=============================================================================
  Admin: Create Per-User Workspaces
  Run as ACCOUNTADMIN on SFSENORTHAMERICA-HOL_CARNIVAL
  
  Creates a shared workspace per HOL user so they can open their SQL files
  directly in Snowsight without needing GitHub.
=============================================================================*/

USE ROLE ACCOUNTADMIN;

-- Create a database to hold the workspaces
CREATE DATABASE IF NOT EXISTS HOL_WORKSPACES;
CREATE SCHEMA IF NOT EXISTS HOL_WORKSPACES.PUBLIC;

-- Create 10 shared workspaces (one per user)
CREATE WORKSPACE IF NOT EXISTS HOL_WORKSPACES.PUBLIC.USER_HOL_01;
CREATE WORKSPACE IF NOT EXISTS HOL_WORKSPACES.PUBLIC.USER_HOL_02;
CREATE WORKSPACE IF NOT EXISTS HOL_WORKSPACES.PUBLIC.USER_HOL_03;
CREATE WORKSPACE IF NOT EXISTS HOL_WORKSPACES.PUBLIC.USER_HOL_04;
CREATE WORKSPACE IF NOT EXISTS HOL_WORKSPACES.PUBLIC.USER_HOL_05;
CREATE WORKSPACE IF NOT EXISTS HOL_WORKSPACES.PUBLIC.USER_HOL_06;
CREATE WORKSPACE IF NOT EXISTS HOL_WORKSPACES.PUBLIC.USER_HOL_07;
CREATE WORKSPACE IF NOT EXISTS HOL_WORKSPACES.PUBLIC.USER_HOL_08;
CREATE WORKSPACE IF NOT EXISTS HOL_WORKSPACES.PUBLIC.USER_HOL_09;
CREATE WORKSPACE IF NOT EXISTS HOL_WORKSPACES.PUBLIC.USER_HOL_10;

-- Grant WRITE access to each user's workspace (so they can edit files)
GRANT WRITE ON WORKSPACE HOL_WORKSPACES.PUBLIC.USER_HOL_01 TO ROLE HOL_USER_01_ROLE;
GRANT WRITE ON WORKSPACE HOL_WORKSPACES.PUBLIC.USER_HOL_02 TO ROLE HOL_USER_02_ROLE;
GRANT WRITE ON WORKSPACE HOL_WORKSPACES.PUBLIC.USER_HOL_03 TO ROLE HOL_USER_03_ROLE;
GRANT WRITE ON WORKSPACE HOL_WORKSPACES.PUBLIC.USER_HOL_04 TO ROLE HOL_USER_04_ROLE;
GRANT WRITE ON WORKSPACE HOL_WORKSPACES.PUBLIC.USER_HOL_05 TO ROLE HOL_USER_05_ROLE;
GRANT WRITE ON WORKSPACE HOL_WORKSPACES.PUBLIC.USER_HOL_06 TO ROLE HOL_USER_06_ROLE;
GRANT WRITE ON WORKSPACE HOL_WORKSPACES.PUBLIC.USER_HOL_07 TO ROLE HOL_USER_07_ROLE;
GRANT WRITE ON WORKSPACE HOL_WORKSPACES.PUBLIC.USER_HOL_08 TO ROLE HOL_USER_08_ROLE;
GRANT WRITE ON WORKSPACE HOL_WORKSPACES.PUBLIC.USER_HOL_09 TO ROLE HOL_USER_09_ROLE;
GRANT WRITE ON WORKSPACE HOL_WORKSPACES.PUBLIC.USER_HOL_10 TO ROLE HOL_USER_10_ROLE;

-- Also grant USAGE on the database/schema so they can see the workspaces
GRANT USAGE ON DATABASE HOL_WORKSPACES TO ROLE HOL_USER_01_ROLE;
GRANT USAGE ON DATABASE HOL_WORKSPACES TO ROLE HOL_USER_02_ROLE;
GRANT USAGE ON DATABASE HOL_WORKSPACES TO ROLE HOL_USER_03_ROLE;
GRANT USAGE ON DATABASE HOL_WORKSPACES TO ROLE HOL_USER_04_ROLE;
GRANT USAGE ON DATABASE HOL_WORKSPACES TO ROLE HOL_USER_05_ROLE;
GRANT USAGE ON DATABASE HOL_WORKSPACES TO ROLE HOL_USER_06_ROLE;
GRANT USAGE ON DATABASE HOL_WORKSPACES TO ROLE HOL_USER_07_ROLE;
GRANT USAGE ON DATABASE HOL_WORKSPACES TO ROLE HOL_USER_08_ROLE;
GRANT USAGE ON DATABASE HOL_WORKSPACES TO ROLE HOL_USER_09_ROLE;
GRANT USAGE ON DATABASE HOL_WORKSPACES TO ROLE HOL_USER_10_ROLE;

GRANT USAGE ON SCHEMA HOL_WORKSPACES.PUBLIC TO ROLE HOL_USER_01_ROLE;
GRANT USAGE ON SCHEMA HOL_WORKSPACES.PUBLIC TO ROLE HOL_USER_02_ROLE;
GRANT USAGE ON SCHEMA HOL_WORKSPACES.PUBLIC TO ROLE HOL_USER_03_ROLE;
GRANT USAGE ON SCHEMA HOL_WORKSPACES.PUBLIC TO ROLE HOL_USER_04_ROLE;
GRANT USAGE ON SCHEMA HOL_WORKSPACES.PUBLIC TO ROLE HOL_USER_05_ROLE;
GRANT USAGE ON SCHEMA HOL_WORKSPACES.PUBLIC TO ROLE HOL_USER_06_ROLE;
GRANT USAGE ON SCHEMA HOL_WORKSPACES.PUBLIC TO ROLE HOL_USER_07_ROLE;
GRANT USAGE ON SCHEMA HOL_WORKSPACES.PUBLIC TO ROLE HOL_USER_08_ROLE;
GRANT USAGE ON SCHEMA HOL_WORKSPACES.PUBLIC TO ROLE HOL_USER_09_ROLE;
GRANT USAGE ON SCHEMA HOL_WORKSPACES.PUBLIC TO ROLE HOL_USER_10_ROLE;

-- Verify
SHOW WORKSPACES IN SCHEMA HOL_WORKSPACES.PUBLIC;

SELECT 'All 10 workspaces created and granted.' AS status;
