/*=============================================================================
  Section 9: Cleanup
  Carnival Gaming HOL -- User 05
  
  Run this script to clean up all objects created during the lab.
  This is OPTIONAL -- only run if instructed to do so.
=============================================================================*/

USE ROLE HOL_USER_05_ROLE;
USE WAREHOUSE HOL_USER_05_WH;
USE DATABASE HOL_USER_05_DB;

-- Drop Dynamic Tables first (they depend on raw tables)
DROP DYNAMIC TABLE IF EXISTS ANALYTICS.DAILY_SHIP_REVENUE;
DROP DYNAMIC TABLE IF EXISTS ANALYTICS.VOYAGE_PERFORMANCE;
DROP DYNAMIC TABLE IF EXISTS HARMONIZED.GAMING_TRANSACTIONS_H;
DROP DYNAMIC TABLE IF EXISTS HARMONIZED.PLAYER_SUMMARY_H;

-- Drop Cortex Search Service
DROP CORTEX SEARCH SERVICE IF EXISTS ANALYTICS.REVIEW_SEARCH;

-- Drop Semantic View
DROP SEMANTIC VIEW IF EXISTS ANALYTICS.GAMING_SEMANTIC_MODEL;

-- Drop views
DROP VIEW IF EXISTS ANALYTICS.ENRICHED_REVIEWS;

-- Drop governance objects (must remove policies before dropping tables)
ALTER TABLE RAW_GAMING.PLAYERS MODIFY COLUMN email UNSET MASKING POLICY;
ALTER TABLE RAW_GAMING.PLAYERS MODIFY COLUMN phone UNSET MASKING POLICY;
ALTER TABLE RAW_GAMING.PLAYERS MODIFY COLUMN first_name UNSET MASKING POLICY;
ALTER TABLE RAW_GAMING.PLAYERS MODIFY COLUMN last_name UNSET MASKING POLICY;
ALTER TABLE RAW_GAMING.SHIPS DROP ROW ACCESS POLICY IF EXISTS BRAND_ROW_POLICY;

DROP MASKING POLICY IF EXISTS RAW_GAMING.EMAIL_MASK;
DROP MASKING POLICY IF EXISTS RAW_GAMING.PHONE_MASK;
DROP MASKING POLICY IF EXISTS RAW_GAMING.NAME_MASK;
DROP ROW ACCESS POLICY IF EXISTS RAW_GAMING.BRAND_ROW_POLICY;
DROP TAG IF EXISTS RAW_GAMING.PII_TYPE;
DROP TAG IF EXISTS RAW_GAMING.SENSITIVITY_LEVEL;

-- Drop schemas (cascades all remaining objects)
DROP SCHEMA IF EXISTS COLLABORATION CASCADE;
DROP SCHEMA IF EXISTS ANALYTICS CASCADE;
DROP SCHEMA IF EXISTS HARMONIZED CASCADE;
DROP SCHEMA IF EXISTS RAW_GAMING CASCADE;

-- Suspend warehouse to stop billing
ALTER WAREHOUSE HOL_USER_05_WH SUSPEND;

SELECT 'Cleanup complete for User 05!' AS status;
